export { default as addOtherData } from './addOtherData'
export { default as getOtherData } from './getOtherData'
export { default as storeDeletedId } from './storeDeletedId'
export { default as updateOtherData } from './updateOtherData'
export { default as updateBookCount } from './updateBookCount'
